<?php

  $lang_translate = $array = array(
      //login errors
      "Não foi possível iniciar uma sessão segura!" => "Unable to start a secure session!",
      "Não há conexão com Banco de dados!" => "There is no connection to the Database!",
      "Por Favor Responda a reCAPTCHA!" => "Please respond to reCAPTCHA!",
      "Login e/ou Senha incorreto(s)!" => "Incorrect login and/or password!",
      "Sua conta foi bloqueada! '
    . 'Foi enviado para o seu e-mail instruções para o desbloqueio!" => "Your account has been blocked! Instructions for unlocking have been sent to your email!",
      "Sua conta foi bloqueada! '
    . 'Erro ao enviar e-mail de desboqueio, Entre em contato conosco!" => "Your account has been blocked! Error sending unblocking email, Contact us!",
      "Sua conta ainda está desativada!'
    . ' Acesse o e-mail enviado no momento do cadastro para ativá-la." => "Your account is still deactivated! Access the email sent when registering to activate it.",
      "Não foi possível iniciar uma sessão segura!" => "Unable to start a secure session!",
      "Ocorreu um erro na resposta do reCAPTCHA, tente novamente!" => "An error occurred in the reCAPTCHA response, please try again!",
      "Existem campos em branco!" => "There are blank fields!",
      //menu
      "Conecte-se" => "Login",
      "Perfil" => "Profile",
      "Dashboard" => "Dashboard",
      "Tickets" => "Tickets",
      "Usuários" => "Users",
      "Usuário" => "User",
      "Cadastrar Usuário" => "Register User",
      "Sair" => "Exit",
      "Configurações" => "Settings",
      //forms options
      "Visualizar" => "View",
      "Cadastrar" => "Register",
      "Atualizar" => "Update",
      "Cancelar" => "Cancel",
      "Salvar" => "Save",
      "Voltar" => "Back",
      "Ativo" => "Active",
      "Bloqueado" => "Blocked",
      //forms fields
      "UID" => "UID",
      "Data" => "Date",
      "CPF" => "CPF",
      "Nome" => "Name",
      "Email" => "Email",
      "Senha" => "Password",
      "Nascimento" => "Birth",
      "Celular" => "Phone",
      "Sexo" => "Gender",
      "Feminino" => "Feminine",
      "Masculino" => "Masculine",
      "Status" => "Status",
      "Ativo" => "Active",
      "Inativo" => "Inactive",
      "Bloqueado" => "Blocked",
      "Privilégios" => "Privileges",
      //users    
      "Consultar pelo nome" => "Search by name",
      "Nenhum usuário encontrado!" => "No users found!",
      "Consultar" => "Search",
      "Limpar" => "Clear",
      //forms profile
      "Alterar Foto" => "Change photo",
      "Alterar Senha" => "Change Password",
      "Senha Atual" => "Current password",
      "Nova Senha" => "New Password",
      "Confirmar Senha" => "Confirm password",
      "Alterar Foto do Perfil" => "Change Profile Photo",
      "Clique para selecionar a foto!" => "Click to select photo!",
      "Não é permitido campos em branco!" => "No blank fields allowed!",
      //forms profile message
      "Digite seu nome" => "Enter your name",
      "Digite seu cpf" => "Enter your cpf",
      "Digite sua data de nascimento" => "Enter your birth date",
      "Digite seu celular" => "Enter your cell phone",
      "Digite seu email" => "Enter your email",
      "seuemail@email.com" => "youremail@email.com",
      //forms general message
      "Digite um nome" => "Enter a Name",
      "Digite um CPF" => "Enter a CPF",
      "Digite um email" => "Enter a Email",
      "Digite uma data" => "Enter a date",
      "Digite uma Senha" => "Enter a Password",
      "Data de nascimento" => "Enter a Birth",
      "Digite um celular" => "Enter a Phone",
      //form return messages
      "Salvo com sucesso!" => "Saved successfully",
      "Alteração realizada com sucesso!" => "Change made successfully!",
      "Cadastro realizado com sucesso!" => "Registration completed successfully!",
      "Erro ao realizar alteração!" => "Error when making changes!",
      "Não é permitido campos em branco!" => "No blank fields allowed!",
      "Erro ao fazer upload da imagem!" => "Error uploading image!",
      "O tamanho da imagem excede o tamanho permitido de 5mb!" => "The image size exceeds the allowed size of 5mb!",
      "Ocorreu um erro no upload da imagem!" => "An error occurred while uploading the image!",
      "O formato da imagem é inválido! Formatos aceitos: Gif, Jpeg, Jpg e Png!" => "The image format is invalid! Accepted formats: Gif, Jpeg, Jpg and Png!",
      "Imagem excluída com sucesso!" => "Image deleted successfully!",
      "Erro ao excluir imagem!" => "Error deleting image!",
      "A senha deve ter pelo menos 8 caracteres. Por favor, digite novamente!" => "The password must be at least 8 characters long. Please type again!",
      "A senha deve conter números e letras (maiúscula e minúscula)!" => "The password must contain numbers and letters (upper and lower case)!",
      "A senha não pode ficar em branco!" => "The password cannot be left blank!",
      "A nova senha e a confirmação da senha não coincidem!" => "The new password and password confirmation do not match!",
      "O campo da confirmação da senha não pode está em branco!" => "The password confirmation field cannot be blank!",
      "Campo Obrigatório!" => "Required field!",
      "CPF inválido!" => "Invalid CPF!",
      "Não foi encontrado usuário cadastrado!" => "No registered user found!",
      //return permissions
      "Você não tem permissão para visualizar esta página!" => "You do not have permission to view this page!",
      "" => "",
      "" => "",
      //forms general
      "Selecione" => "Select",
      "" => "",
      "" => "",
      "" => ""
  );
  